export enum PathAPI {
  Root = '/',
  Auth = '/auth',
  AppSettings = '/app-settings',
  AddCategory = '/add-category',
  User = '/user',
  Users = '/users',
  ChangeStatus = '/change-status',
  ChangeRights = '/change-rights',
  Login = '/login',
  Logout = '/logout',
  Register = '/register',
  ChangeAvatar = '/change-avatar',
  CreateReview = '/create-review',
  EditReview = '/edit-review',
  Reviews = '/reviews',
  Review = '/review',
  Social = '/social',
  Like = '/like',
  Star = '/star',
  Tag = '/tag',
  Delete = '/delete',
  CreateComment = '/create-comment',
}
